[build]
  command = "pip install -r requirements.txt && python ravs_screener.py"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "http://134.122.18.23/api/:splat"
  status = 200
  force = true
